
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/ambro/AppData/Local/Temp/build-env-my4u256k/Lib/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Windows - 10.0.26100 - AMD64
...
