# Trigger del workflow: si attiva ad ogni push e pull request
on:
  push: {} # Si attiva su push a qualsiasi branch
  pull_request: {} # Si attiva su pull request verso qualsiasi branch

jobs:
  # Job per costruire le wheel su Windows
  windows-build:
    name: Build Windows (x64) Python ${{ matrix.PYVERSION }}
    runs-on: windows-latest
    env:
      PYVERSION: ${{ matrix.PYVERSION }}
      CI_ARCH: "64" 
      CI_WINDOWS: "1"
    strategy:
      fail-fast: false
      matrix:
        PYVERSION: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.PYVERSION }} (x64)
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.PYVERSION }}
          architecture: 'x64'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Run C/C++ code vendoring script
        # Questo script prepara la directory 'synthizer-vendored' con il codice C/C++
        # Assicurati che il percorso 'synthizer-c/vendor.py' sia corretto.
        run: python synthizer-c/vendor.py synthizer-vendored

      - name: Cache Pip (Windows)
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ env.PYVERSION }}-${{ env.CI_ARCH }}-${{ hashFiles('**/requirements.txt', '**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ env.PYVERSION }}-${{ env.CI_ARCH }}-

      - name: Configure MSVC 64-bit Environment Variables
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          echo "Configured MSVC for x64"
          set PATH >> %GITHUB_ENV%
          set INCLUDE >> %GITHUB_ENV%
          set LIB >> %GITHUB_ENV%

      - name: Install build dependencies (Windows)
        run: |
          python -m pip install --upgrade pip 
          pip install ninja cmake wheel tomli setuptools packaging distro scikit-build cython

      - name: Build Python Wheels (Windows)
        shell: powershell
        run: |
          Set-Location $Env:GITHUB_WORKSPACE
          python setup.py bdist_wheel

      - name: Upload Python Wheel Artifact (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels-win-x64-${{ matrix.PYVERSION }}
          path: dist/*.whl

  # Job per costruire le wheel su Linux
  linux-build:
    name: Build Linux (x64) Python ${{ matrix.PYVERSION }}
    runs-on: ubuntu-latest
    env:
      PYVERSION: ${{ matrix.PYVERSION }}
      CI_ARCH: "64" 
    strategy:
      fail-fast: false
      matrix:
        PYVERSION: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.PYVERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.PYVERSION }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Run C/C++ code vendoring script
        run: python synthizer-c/vendor.py synthizer-vendored

      - name: Cache Pip (Linux)
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ env.PYVERSION }}-${{ hashFiles('**/requirements.txt', '**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ env.PYVERSION }}-

      - name: Install system build dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential 

      - name: Install Python build dependencies (Linux)
        run: |
          python -m pip install --upgrade pip 
          pip install ninja cmake wheel tomli setuptools packaging distro scikit-build cython

      - name: Build Python Wheels (Linux)
        run: |
          python setup.py bdist_wheel

      - name: Upload Python Wheel Artifact (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels-linux-x64-${{ matrix.PYVERSION }}
          path: dist/*.whl

  # Job per costruire le wheel su macOS
  macos-build:
    name: Build macOS (${{ matrix.ARCH }}) Python ${{ matrix.PYVERSION }} 
    runs-on: macos-latest # Questo runner è macos-14-arm64
    env:
      PYVERSION: ${{ matrix.PYVERSION }}
      TARGET_ARCH: ${{ matrix.ARCH }} 
    strategy:
      fail-fast: false
      matrix:
        PYVERSION: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        ARCH: ["arm64", "x64"] 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install and set up gettext for x64 Python
        # Applica per Python 3.8, 3.9, e 3.10 su x64, che sono le versioni problematiche
        if: matrix.ARCH == 'x64' && (matrix.PYVERSION == '3.8' || matrix.PYVERSION == '3.9' || matrix.PYVERSION == '3.10')
        run: |
          echo "Attempting to install gettext for x64 environment on ARM64 runner..."
          # Su un runner ARM64 (come macos-14-arm64), per installare pacchetti x86_64 con Homebrew,
          # Homebrew stesso deve essere eseguito sotto l'emulazione Rosetta 2.
          # Il prefisso di installazione per i pacchetti x86_64 di Homebrew su un Mac Apple Silicon è /usr/local.
          # Il prefisso per i pacchetti arm64 nativi è /opt/homebrew.
          # L'errore indica che Python x64 cerca in /usr/local/opt/gettext.
          
          # Assicuriamoci che brew installi la versione corretta (potrebbe essere necessario arch -x86_64 brew install)
          # Tuttavia, GitHub Actions runner potrebbero già avere un setup di Homebrew per x86_64.
          # Per ora, proviamo un semplice brew install. Se fallisce, potrebbe essere necessario forzare l'architettura.
          brew install gettext
          
          GETTEXT_X64_PREFIX="/usr/local/opt/gettext" # Percorso per pacchetti x64 su macOS (Intel o Rosetta)
          
          if [ -d "${GETTEXT_X64_PREFIX}/lib" ]; then
            echo "Found gettext lib for x64 at ${GETTEXT_X64_PREFIX}/lib"
            echo "Prepending ${GETTEXT_X64_PREFIX}/lib to DYLD_LIBRARY_PATH"
            echo "DYLD_LIBRARY_PATH=${GETTEXT_X64_PREFIX}/lib${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}" >> $GITHUB_ENV
            
            echo "Prepending ${GETTEXT_X64_PREFIX}/bin to PATH"
            echo "${GETTEXT_X64_PREFIX}/bin" >> $GITHUB_PATH
            echo "DYLD_LIBRARY_PATH (from GITHUB_ENV will be): ${GETTEXT_X64_PREFIX}/lib"
          else
            echo "Error: ${GETTEXT_X64_PREFIX}/lib not found after attempting brew install."
            echo "This might indicate an issue with Homebrew setup for x64 packages on this runner or gettext installation."
            # Considera di fallire lo step se gettext non può essere configurato correttamente
            # exit 1 
          fi
          echo "--- End of gettext setup ---"

      - name: Set up Python ${{ matrix.PYVERSION }} (${{ matrix.ARCH }})
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.PYVERSION }}
          architecture: ${{ matrix.ARCH }} 

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Run C/C++ code vendoring script
        run: python synthizer-c/vendor.py synthizer-vendored

      - name: Cache Pip (macOS ${{ matrix.ARCH }})
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-pip-${{ matrix.ARCH }}-${{ env.PYVERSION }}-${{ hashFiles('**/requirements.txt', '**/setup.py') }} 
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.ARCH }}-${{ env.PYVERSION }}-

      - name: Install Python build dependencies (macOS)
        run: |
          python -m pip install --upgrade pip 
          pip install ninja cmake wheel tomli setuptools packaging distro scikit-build cython
          
      - name: Build Python Wheels (macOS ${{ matrix.ARCH }})
        run: |
          echo "Current DYLD_LIBRARY_PATH: $DYLD_LIBRARY_PATH" # Per debug
          echo "Current PATH: $PATH" # Per debug
          python setup.py bdist_wheel

      - name: Upload Python Wheel Artifact (macOS ${{ matrix.ARCH }})
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels-macos-${{ matrix.ARCH }}-${{ matrix.PYVERSION }} 
          path: dist/*.whl

  # Job per creare la sdist (source distribution)
  sdist-build:
    name: Build Python sdist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python (for sdist)
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' 
      
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Run C/C++ code vendoring script
        run: python synthizer-c/vendor.py synthizer-vendored

      - name: Install Python build dependencies (sdist)
        run: |
          python -m pip install --upgrade pip 
          pip install ninja cmake wheel tomli setuptools packaging distro scikit-build cython

      - name: Build Python sdist
        run: python setup.py sdist

      - name: Upload Python sdist Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-sdist
          path: dist/*.tar.gz 

  # Job per il deployment su PyPI
  deploy_pypi:
    name: Deploy to PyPI
    if: startsWith(github.ref, 'refs/tags') 
    needs: [windows-build, linux-build, macos-build, sdist-build] 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write 
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ~/artifacts 

      - name: Set up Python for Twine
        uses: actions/setup-python@v5
        with:
          python-version: '3.x' 
      
      - name: Upgrade pip for Twine step 
        run: python -m pip install --upgrade pip

      - name: Install Twine
        run: python -m pip install --upgrade twine

      - name: Display downloaded artifacts structure
        run: ls -R ~/artifacts

      - name: Upload to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }} 
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }} 
        run: |
          python -m twine upload --skip-existing ~/artifacts/*/*
