# Trigger del workflow: si attiva ad ogni push e pull request
on:
  push: {} # Si attiva su push a qualsiasi branch
  pull_request: {} # Si attiva su pull request verso qualsiasi branch

jobs:
  # Job per costruire le wheel su Windows
  windows-build:
    name: Build Windows (${{ matrix.CI_ARCH }}) Python ${{ matrix.PYVERSION }}
    runs-on: windows-latest
    env:
      PYVERSION: ${{ matrix.PYVERSION }}
      CI_ARCH_LOWER: ${{ (matrix.CI_ARCH == 'x86' && 'x86' || 'x64') }}
      CI_WINDOWS: "1"
      CI_ARCH_ENV: ${{ matrix.CI_ARCH }}
      VCPKG_DEFAULT_TRIPLET: ${{ (matrix.CI_ARCH == 'x86' && 'x86-windows' || 'x64-windows') }}
    strategy:
      fail-fast: false
      matrix:
        PYVERSION: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        CI_ARCH: ["x64", "x86"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.PYVERSION }} (${{ env.CI_ARCH_LOWER }})
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.PYVERSION }}
          architecture: ${{ env.CI_ARCH_LOWER }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Run C/C++ code vendoring script
        run: python synthizer-c/vendor.py synthizer-vendored

      - name: Cache Pip (Windows ${{ matrix.CI_ARCH }})
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ env.PYVERSION }}-${{ matrix.CI_ARCH }}-${{ hashFiles('**/requirements.txt', '**/setup.py', 'vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ env.PYVERSION }}-${{ matrix.CI_ARCH }}-

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ env.CI_ARCH_LOWER }}

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Install dependencies using vcpkg (Windows)
        shell: pwsh
        run: |
          Write-Host "VCPKG_ROOT is $env:VCPKG_ROOT"
          Write-Host "VCPKG_DEFAULT_TRIPLET is $env:VCPKG_DEFAULT_TRIPLET"
          vcpkg.exe install --triplet $env:VCPKG_DEFAULT_TRIPLET
          $vcpkgInstalledPath = "$env:VCPKG_ROOT/installed/$env:VCPKG_DEFAULT_TRIPLET"
          echo "CMAKE_PREFIX_PATH=$vcpkgInstalledPath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Host "CMAKE_PREFIX_PATH set to $vcpkgInstalledPath"

      - name: Install Python build dependencies (Windows)
        run: |
          python -m pip install --upgrade pip
          pip install ninja cmake wheel tomli setuptools packaging distro scikit-build cython build

      - name: Build Python Wheels (Windows ${{ matrix.CI_ARCH }})
        shell: powershell
        env: # Assicura che CMAKE_PREFIX_PATH sia disponibile qui se python -m build lo necessita
          CMAKE_PREFIX_PATH: ${{ env.CMAKE_PREFIX_PATH }}
        run: |
          Set-Location $Env:GITHUB_WORKSPACE
          Write-Host "Building with CMAKE_PREFIX_PATH = $env:CMAKE_PREFIX_PATH"
          python -m build --wheel --no-isolation

      - name: Add vcpkg libraries to Wheel (Windows ${{ matrix.CI_ARCH }})
        shell: powershell
        run: |
          $wheelFile = Get-ChildItem -Path dist/*.whl | Select-Object -First 1
          if (-not $wheelFile) {
            Write-Error "No wheel file found in dist/"
            exit 1
          }
          $originalWheelPath = $wheelFile.FullName
          Write-Host "Modifying wheel: $originalWheelPath"

          # Crea un percorso temporaneo per il file .zip
          $tempZipPath = Join-Path $wheelFile.DirectoryName ($wheelFile.BaseName + ".zip")

          # Copia .whl in .zip per Expand-Archive
          Write-Host "Copying $originalWheelPath to $tempZipPath for extraction."
          Copy-Item -Path $originalWheelPath -Destination $tempZipPath -Force
          
          $vcpkgTripletBinDir = "$env:VCPKG_ROOT/installed/$env:VCPKG_DEFAULT_TRIPLET/bin"
          Write-Host "Source directory for DLLs: $vcpkgTripletBinDir"

          $tempExtractDir = ".\temp_wheel_extracted"
          Remove-Item -Path $tempExtractDir -Recurse -Force -ErrorAction SilentlyContinue
          New-Item -ItemType Directory -Path $tempExtractDir

          Write-Host "Extracting $tempZipPath to $tempExtractDir"
          Expand-Archive -LiteralPath $tempZipPath -DestinationPath $tempExtractDir -Force

          $targetDirInWheel = Join-Path $tempExtractDir "synthizer" # Il nome del tuo package
          if (-not (Test-Path $targetDirInWheel)) {
            Write-Host "Target package directory $targetDirInWheel does not exist in wheel, creating it."
            New-Item -ItemType Directory -Path $targetDirInWheel -Force
          }

          if (Test-Path $vcpkgTripletBinDir) {
            Write-Host "Copying DLLs from $vcpkgTripletBinDir to $targetDirInWheel"
            Get-ChildItem -Path $vcpkgTripletBinDir -Filter *.dll -File | ForEach-Object {
                Copy-Item -Path $_.FullName -Destination $targetDirInWheel -Force
                Write-Host "Copied $($_.Name) to $targetDirInWheel"
            }
          } else {
            Write-Warning "$vcpkgTripletBinDir not found. No DLLs will be copied."
          }

          Write-Host "Re-packaging wheel from $tempExtractDir to $originalWheelPath"
          # Comprimi il contenuto della directory estratta e sovrascrivi il file .whl originale
          Compress-Archive -Path "$tempExtractDir\*" -DestinationPath $originalWheelPath -Force

          # Pulisci i file temporanei
          Remove-Item -Path $tempExtractDir -Recurse -Force
          Remove-Item -Path $tempZipPath -Force
          Write-Host "Windows wheel modification complete for $originalWheelPath"

      - name: Upload Python Wheel Artifact (Windows ${{ matrix.CI_ARCH }})
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels-win-${{ matrix.CI_ARCH }}-${{ matrix.PYVERSION }}
          path: dist/*.whl

  # Job per costruire le wheel su Linux
  linux-build:
    name: Build Linux (x64) Python ${{ matrix.PYVERSION }}
    runs-on: ubuntu-latest
    env:
      PYVERSION: ${{ matrix.PYVERSION }}
      CI_ARCH: "x64"
      VCPKG_DEFAULT_TRIPLET: "x64-linux"
    strategy:
      fail-fast: false
      matrix:
        PYVERSION: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.PYVERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.PYVERSION }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Run C/C++ code vendoring script
        run: python synthizer-c/vendor.py synthizer-vendored

      - name: Cache Pip (Linux)
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ env.PYVERSION }}-${{ hashFiles('**/requirements.txt', '**/setup.py', 'vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ env.PYVERSION }}-

      - name: Install system build dependencies (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential patchelf

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgTriplet: ${{ env.VCPKG_DEFAULT_TRIPLET }}

      - name: Install dependencies using vcpkg (Linux)
        run: |
          echo "VCPKG_ROOT is $VCPKG_ROOT"
          $VCPKG_ROOT/vcpkg install --triplet $VCPKG_DEFAULT_TRIPLET
          VCPKG_INSTALLED_PATH="$VCPKG_ROOT/installed/$VCPKG_DEFAULT_TRIPLET"
          echo "CMAKE_PREFIX_PATH=$VCPKG_INSTALLED_PATH" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=$VCPKG_INSTALLED_PATH/lib:\$LD_LIBRARY_PATH" >> $GITHUB_ENV # For auditwheel to find libs
          echo "CMAKE_PREFIX_PATH set to $VCPKG_INSTALLED_PATH"
          echo "LD_LIBRARY_PATH extended with $VCPKG_INSTALLED_PATH/lib"

      - name: Install Python build dependencies (Linux)
        run: |
          python -m pip install --upgrade pip
          pip install ninja cmake wheel tomli setuptools packaging distro scikit-build cython build auditwheel

      - name: Build Python Wheels (Linux)
        run: |
          echo "Building with CMAKE_PREFIX_PATH = $CMAKE_PREFIX_PATH"
          python -m build --wheel --no-isolation

      - name: Repair Wheel with Auditwheel (Linux)
        run: |
          for wheel in dist/*.whl; do
            auditwheel repair "$wheel" --plat manylinux_2_28_x86_64 -w dist/ # Or your desired manylinux tag
          done
          # Remove original (unrepaired) wheels if different, auditwheel might overwrite or create new ones
          # ls dist/

      - name: Upload Python Wheel Artifact (Linux)
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels-linux-x64-${{ matrix.PYVERSION }}
          path: dist/*-manylinux*.whl # Upload only repaired wheels

  # Job per costruire le wheel su macOS (x64 - Intel Runner)
  macos-x64-build:
    name: Build macOS (x64) Python ${{ matrix.PYVERSION }}
    runs-on: macos-13 # Intel runner
    env:
      PYVERSION: ${{ matrix.PYVERSION }}
      TARGET_ARCH: "x64"
      VCPKG_DEFAULT_TRIPLET: "x64-osx"
    strategy:
      fail-fast: false
      matrix:
        PYVERSION: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.PYVERSION }} (x64)
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.PYVERSION }}
          architecture: 'x64'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Run C/C++ code vendoring script
        run: python synthizer-c/vendor.py synthizer-vendored

      - name: Cache Pip (macOS x64)
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-${{ env.TARGET_ARCH }}-pip-${{ env.PYVERSION }}-${{ hashFiles('**/requirements.txt', '**/setup.py', 'vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.TARGET_ARCH }}-pip-${{ env.PYVERSION }}-

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgTriplet: ${{ env.VCPKG_DEFAULT_TRIPLET }}

      - name: Install dependencies using vcpkg (macOS x64)
        run: |
          echo "VCPKG_ROOT is $VCPKG_ROOT"
          $VCPKG_ROOT/vcpkg install --triplet $VCPKG_DEFAULT_TRIPLET
          VCPKG_INSTALLED_PATH="$VCPKG_ROOT/installed/$VCPKG_DEFAULT_TRIPLET"
          echo "CMAKE_PREFIX_PATH=$VCPKG_INSTALLED_PATH" >> $GITHUB_ENV
          echo "DYLD_LIBRARY_PATH=$VCPKG_INSTALLED_PATH/lib:\$DYLD_LIBRARY_PATH" >> $GITHUB_ENV # For delocate to find libs
          echo "CMAKE_PREFIX_PATH set to $VCPKG_INSTALLED_PATH"
          echo "DYLD_LIBRARY_PATH extended with $VCPKG_INSTALLED_PATH/lib"


      - name: Install Python build dependencies (macOS)
        run: |
          python -m pip install --upgrade pip
          pip install ninja cmake wheel tomli setuptools packaging distro scikit-build cython build delocate

      - name: Build Python Wheels (macOS x64)
        run: |
          echo "Building with CMAKE_PREFIX_PATH = $CMAKE_PREFIX_PATH"
          python -m build --wheel --no-isolation

      - name: Repair Wheel with Delocate (macOS x64)
        run: |
          for wheel in dist/*.whl; do
            delocate-wheel -w dist/ "$wheel" # delocate will place repaired wheel in dist/
          done
          # ls dist/

      - name: Upload Python Wheel Artifact (macOS x64)
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels-macos-x64-${{ matrix.PYVERSION }}
          path: dist/*.whl # Upload all wheels, delocate might overwrite

  # Job per costruire le wheel su macOS (ARM64 - ARM Runner)
  macos-arm64-build:
    name: Build macOS (arm64) Python ${{ matrix.PYVERSION }}
    runs-on: macos-latest # Should pick an ARM runner like macos-14
    env:
      PYVERSION: ${{ matrix.PYVERSION }}
      TARGET_ARCH: "arm64"
      VCPKG_DEFAULT_TRIPLET: "arm64-osx"
    strategy:
      fail-fast: false
      matrix:
        PYVERSION: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python ${{ matrix.PYVERSION }} (arm64)
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.PYVERSION }}
          architecture: 'arm64'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Run C/C++ code vendoring script
        run: python synthizer-c/vendor.py synthizer-vendored

      - name: Cache Pip (macOS arm64)
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/pip
          key: ${{ runner.os }}-${{ env.TARGET_ARCH }}-pip-${{ env.PYVERSION }}-${{ hashFiles('**/requirements.txt', '**/setup.py', 'vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.TARGET_ARCH }}-pip-${{ env.PYVERSION }}-

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgTriplet: ${{ env.VCPKG_DEFAULT_TRIPLET }}

      - name: Install dependencies using vcpkg (macOS arm64)
        run: |
          echo "VCPKG_ROOT is $VCPKG_ROOT"
          $VCPKG_ROOT/vcpkg install --triplet $VCPKG_DEFAULT_TRIPLET
          VCPKG_INSTALLED_PATH="$VCPKG_ROOT/installed/$VCPKG_DEFAULT_TRIPLET"
          echo "CMAKE_PREFIX_PATH=$VCPKG_INSTALLED_PATH" >> $GITHUB_ENV
          echo "DYLD_LIBRARY_PATH=$VCPKG_INSTALLED_PATH/lib:\$DYLD_LIBRARY_PATH" >> $GITHUB_ENV # For delocate to find libs
          echo "CMAKE_PREFIX_PATH set to $VCPKG_INSTALLED_PATH"
          echo "DYLD_LIBRARY_PATH extended with $VCPKG_INSTALLED_PATH/lib"

      - name: Install Python build dependencies (macOS)
        run: |
          python -m pip install --upgrade pip
          pip install ninja cmake wheel tomli setuptools packaging distro scikit-build cython build delocate

      - name: Build Python Wheels (macOS arm64)
        run: |
          echo "Building with CMAKE_PREFIX_PATH = $CMAKE_PREFIX_PATH"
          python -m build --wheel --no-isolation

      - name: Repair Wheel with Delocate (macOS arm64)
        run: |
          for wheel in dist/*.whl; do
            delocate-wheel -w dist/ "$wheel"
          done
          # ls dist/

      - name: Upload Python Wheel Artifact (macOS arm64)
        uses: actions/upload-artifact@v4
        with:
          name: python-wheels-macos-arm64-${{ matrix.PYVERSION }}
          path: dist/*.whl

  # Job per creare la sdist (source distribution)
  sdist-build:
    name: Build Python sdist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python (for sdist)
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Run C/C++ code vendoring script
        run: python synthizer-c/vendor.py synthizer-vendored

      - name: Install Python build dependencies (sdist)
        run: |
          python -m pip install --upgrade pip
          # For sdist, cmake/ninja might not be strictly needed if setup.py/pyproject.toml handles it,
          # but build tools like 'build' are.
          pip install wheel tomli setuptools packaging distro scikit-build cython build

      - name: Build Python sdist
        run: python -m build --sdist

      - name: Upload Python sdist Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-sdist
          path: dist/*.tar.gz

  # Job per il deployment su PyPI
  deploy_pypi:
    name: Deploy to PyPI
    if: startsWith(github.ref, 'refs/tags')
    needs: [windows-build, linux-build, macos-x64-build, macos-arm64-build, sdist-build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for trusted publishing
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ~/artifacts
          # pattern: python-wheels-* # Optional: if you need to be specific, otherwise downloads all
          # merge-multiple: true # If artifacts have same names from different jobs (not the case here)

      - name: Set up Python for Twine
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Upgrade pip for Twine step
        run: python -m pip install --upgrade pip

      - name: Install Twine
        run: python -m pip install --upgrade twine

      - name: Display downloaded artifacts structure
        run: ls -R ~/artifacts

      - name: Upload to PyPI
        env:
          # For trusted publishing, TWINE_USERNAME and TWINE_PASSWORD are not set directly.
          # PyPI should be configured as a trusted publisher in your GitHub Actions settings.
          # If not using trusted publishing, uncomment and use secrets:
          # TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          # TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/ # Or your TestPyPI URL
        run: |
          python -m twine upload --skip-existing ~/artifacts/*/*